# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy project to remote

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
      - name: deploy
        uses: cross-the-world/scp-pipelines@master
        env:
          WECLCOME: 'ssh scp ssh pipelines'
          LASTSSH: 'Doing somrthing after copying'
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          connect-timeout: 10s
          local: ./build/*
          remote: /etc/cangmai/cangmai-web
